Repository TorusNewies/GithubProject, pull requests merged in 2019-09, with the labels that each got.

#6 Añadida licencia
  LICENSE
Labels: documentation

#7 Añadidas plantillas de errores
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#11 Checkeo de estilo con PEP8 y análisis estático de código con dlint
  .circleci/config.yml
Labels: enhancement

#13 Merge: feature/get commits en weekly
  .circleci/config.yml
  python/README.md
  python/esquemas/commitsSchema.jschema
  python/get_repos.py
  python/tests/unitTest.py
Labels: enhancement

#12 Merge feature/CI-CD en weekly
  .circleci/config.yml
  .circleci/requirements.txt
  .circleci/test-requirements.txt
  README.md
  daily/23_09.md
  daily/24_09.md
  daily/26_09.md
  daily/27_09.md
  python/README.md
  python/commitsSchema.jschema
  python/tests/integration/test_integration.py
  python/tests/support/assertions.py
  python/tests/unit/test_get_repos.py
  python/tests/unit/test_graphics.py
Labels: enhancement

#10 Merge: Feature/graficos
  .circleci/config.yml
  .gitignore
  python/README.md
  python/data/test_aut/data.json
  python/data/test_aut/schema
  python/data/test_aut2/data.json
  python/data/test_aut2/schema
  python/graphics-unittest.py
  python/graphics.py
  python/templates/template_1.html
  python/tests/schemas/schema1
  python/tests/schemas/schema2
Labels: enhancement
